### ISSUE TITLE
"My school project"

### ISSUE THREAD

**Issue by Balintskac** [LunaWorks/Orcs-Web#16]
As i told you, i'm developing a database site for my final school homework. i'm little bit stuck at the registration and login part of the side. i didn't even figure out how the problem can be fixed. i would you like ask you to help me on it.
The oldal.php is the main of it, there is a login and registration thing.

**Comment by Balintskac** [comment]
oldal.php

<html>
    <form action="Bejelentkezes.php" method ="post">
        username: <input type="text" name="felhasznalonev"><p>
        password: <input type="password" name="jelszo"><p>
     <input type="submit" name="submit" value="Bejelentkezes"/> <a href="regisztracio.php">Regisztráció?</a>
    </form>
</html>

**Comment by Balintskac** [comment]
Bejelentkezes.php

<?php

session_start();

```
$felhasznalonev = $_POST['felhasznalonev'];
$jelszo = $_POST['jelszo'];

if($felhasznalonev && $jelszo){

    $kapcsolodas = mysql_connect('localhost','root','');
    $adatbazis = mysql_select_db('users',$kapcsolodas);

    $query = mysql_query("SELECT * FROM info WHERE username = '$felhasznalonev'");
    $numrows = mysql_num_rows($query);

if($numrows != 0){
     while($rows = mysql_fetch_assoc($query)){
         $dbfelhasznalonev = $rows['username'];
         $dbjelszo = $rows['password'];
     }

      if($felhasznalonev = $dbfelhasznalonev && md5($jelszo) == $dbjelszo){
         $_SESSION['felhasznalonev'] = $felhasznalonev;

         echo "Bejelentkeztél! <a href='felhasznalo.php'>itt!</a>";
      } else 

         die("Nem megfelelő a jelszó!");
    } else 

        die("nem egyezik meg a felhasználói név és jelszó");

} else 
    die("kérem a felhasználónevet és jelszót!");
```

?>

**Comment by Balintskac** [comment]
regisztracio.php

<?php
if(isset($_POST['submit'])){

$felhasznalonev = strip_tags($_POST['felhasznalonev']);
$email = strip_tags($_POST['email']);
$jelszo = md5(strip_tags($_POST['password']));
$jelszoujra = strip_tags($_POST['repassword']);

if($felhasznalonev&&$email&&$jelszo&&$jelszoujra){
    if($jelszo==$jelszoujra){
        if(6<strlen($jelszo)&&20>=strlen($jelszo)){
            if(4<strlen($felhasznalonev)&&20>=strlen($jelszo)){

```
    $kapcsolodas = mysql_connect('localhost','root','');
    $adatbazis = mysql_select_db('users',$kapcsolodas);

    $query = mysql_query("SELECT * FROM info WHERE username = '$felhasznalonev'");
    $numrows = mysql_num_rows($query);

            if($numrows==0){
            $query2 = mysql_query("SELECT * FROM info WHERE username = '$email'");
            $numrows2 = mysql_num_rows($query2);
                if($numrows == 0){

                    $kapcsolodas = mysql_connect('localhost','root','');
                    $adatbazis = mysql_select_db('users',$kapcsolodas);
                    $password = md5($jelszo);
                    $datum = date("Y-m-d");
                    $query3 = mysql_query("

                    INSERT INTO info VALUES ('','$felhasznalonev','$password','$email','$datum')

                    ");

                    die("Regisztáltál! <a href='oldal.php'>Bejelentkezés</a>");
                } else {
                    echo "ez a email már létezik!";
                }
            } else {
                echo "Ez a felhasználó név már létetzik!";
            }
            echo "Regisztáltál!";
        } else {
            echo "legyen több 4-nél, de 21-nél kevesebb.";
        }
        echo "eddig ok";
    } else {
        echo "legyen több 6-nál, de 21-nél kevesebb.";
    }
    echo "eddig ok";
} else {
echo "nem jó valami!";
}
```

}
else
{
    echo "kérlek töltsd ki!";
}
}
?>
<html>
 <form action="regisztracio.php" method="POST">
    Email:   <input type="text" name="email" value="<?php if(isset($_POST['submit'])){echo $email;} ?>" />
    username: <input type="text" name="felhasznalonev" value="<?php if(isset($_POST['submit'])){echo $felhasznalonev;} ?>" />
    password: <input type="password" name="password" value="<?php if(isset($_POST['submit'])){echo $jelszo;} ?>"/>
    újra:   <input type="password" name="repassword" value="<?php if(isset($_POST['submit'])){echo $jelszoujra;} ?>"/>

```
    <input type="submit" name="submit" value="Regiszráció">
```

</html>

**Comment by Balintskac** [comment]
felhasznalo.php
when the login is successful:

<?php

if(isset($_SESSION['felhasznalonev']))
    echo "Hello".$_SESSION['felhasznalonev']."";
    echo " <a href='kijelentkezes.php'>Kijelentkezés!</a>";  
else
    die("te nem vagy bejelentkezve! itt lehet rá: <a href='oldal.php'>katt rá!</a>");

?>

**Comment by Balintskac** [comment]
kijelentkezes.php
simple log out:

<?php

session_start();

session_destroy();

echo "Kijelentkeztél! A főoldal <a href='oldal.php'>itt!</a>";

?>

**Comment by Moondancer83** [comment]
This in not related to the Orcs project. Create an own project for it. And please commit the code instead of put it in a comment.
