### ISSUE TITLE
Trying issue handling (i'm new here)

### ISSUE THREAD

**Issue by Balintskac** [LunaWorks/Orcs-Web#7]
//Skeleton

**Comment by Moondancer83** [comment]
Hi,
What is the purpose of this issue?
Please define it or use an already existing issue insread.

**Comment by Balintskac** [comment]
Hi!
i was just wondering how it works, i will remove this issue , and get back to the others!

**Comment by Moondancer83** [comment]
Hi,
Don't remove it. Just rename it to "Trying issue handling" for example. Abd if you feel familiar close it.
And please add label "question" to it.

**Comment by Balintskac** [comment]
Okay roger that, i'll do it and make a sense to leave this issue.
